"""Declarative, no-LLM generators for common combinational datapaths.

The JSON-facing API expands a small template request into two artifacts:

* scalar ``.logic`` used as a readable golden model; and
* a bus-aware structural ``.circ`` whose layout is generated by rules.

Adding a circuit family means registering one source/layout expansion here;
generating another width or another named instance is then data-only work.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

import circuitc
from schematic import Schematic, evaluate_circuit, reverse_bits, short_tunnel


_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
SUPPORTED_TEMPLATES = ("mux2", "unsigned_comparator", "unsigned_minmax")


@dataclass(frozen=True)
class Request:
    name: str
    template: str
    width: int


@dataclass
class Expansion:
    source_blocks: list[str]
    layouts: dict[str, ET.Element]
    requests: list[Request]
    main: str


def _pins(prefix: str, width: int) -> str:
    return ", ".join(f"{prefix}{bit}" for bit in range(width))


def parse_spec(data: dict) -> tuple[list[Request], str]:
    """Validate and normalize a version-1 datapath specification."""
    if not isinstance(data, dict):
        raise ValueError("datapath spec must be a JSON object")
    if data.get("version", 1) != 1:
        raise ValueError("only datapath spec version 1 is supported")
    raw = data.get("circuits")
    if not isinstance(raw, list) or not raw:
        raise ValueError("datapath spec needs a non-empty 'circuits' list")
    requests = []
    seen = set()
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise ValueError(f"circuits[{index}] must be an object")
        name = item.get("name")
        template = item.get("template")
        width = item.get("width")
        if not isinstance(name, str) or not _NAME_RE.fullmatch(name):
            raise ValueError(f"invalid circuit name at circuits[{index}]: {name!r}")
        if name in seen:
            raise ValueError(f"duplicate circuit name: {name}")
        if template not in SUPPORTED_TEMPLATES:
            raise ValueError(
                f"unsupported template {template!r}; choose from "
                f"{', '.join(SUPPORTED_TEMPLATES)}")
        if not isinstance(width, int) or isinstance(width, bool) or not 2 <= width <= 16:
            raise ValueError(f"{name}: width must be an integer from 2 through 16")
        requests.append(Request(name, template, width))
        seen.add(name)
    main = data.get("main", requests[0].name)
    if main not in seen:
        raise ValueError(f"main circuit {main!r} is not a requested public circuit")
    return requests, main


def load_spec(path: str | Path) -> tuple[list[Request], str]:
    return parse_spec(json.loads(Path(path).read_text()))


def _compare_stage_source() -> str:
    return """circuit dp_compare_stage:
  inputs LTin, EQin, GTin, A, B
  outputs LTout, EQout, GTout
  different = A ^ B
  same = ~different
  not_a = ~A
  not_b = ~B
  a_lt_b = not_a & B
  a_gt_b = A & not_b
  lt_here = EQin & a_lt_b
  gt_here = EQin & a_gt_b
  LTout = LTin | lt_here
  EQout = EQin & same
  GTout = GTin | gt_here
"""


def _mux2_source() -> str:
    return """circuit dp_mux2:
  inputs D0, D1, S
  outputs Y
  not_s = ~S
  choose_0 = D0 & not_s
  choose_1 = D1 & S
  Y = choose_0 | choose_1
"""


def _comparator_source(name: str, width: int) -> str:
    lines = [f"circuit {name}:",
             f"  inputs {_pins('A', width)}, {_pins('B', width)}",
             "  outputs LT, EQ, GT"]
    lt, eq, gt = "0", "1", "0"
    for bit in range(width - 1, -1, -1):
        final = bit == 0
        next_lt = "LT" if final else f"_lt{bit}"
        next_eq = "EQ" if final else f"_eq{bit}"
        next_gt = "GT" if final else f"_gt{bit}"
        lines.append(
            f"  use dp_compare_stage bit{bit}(LTin={lt}, EQin={eq}, "
            f"GTin={gt}, A=A{bit}, B=B{bit}) -> "
            f"(LTout={next_lt}, EQout={next_eq}, GTout={next_gt})")
        lt, eq, gt = next_lt, next_eq, next_gt
    return "\n".join(lines) + "\n"


def _mux_bank_source(name: str, width: int) -> str:
    lines = [f"circuit {name}:",
             f"  inputs {_pins('D0', width)}, {_pins('D1', width)}, S",
             f"  outputs {_pins('Y', width)}"]
    for bit in range(width):
        lines.append(
            f"  use dp_mux2 bit{bit}(D0=D0{bit}, D1=D1{bit}, S=S) "
            f"-> (Y=Y{bit})")
    return "\n".join(lines) + "\n"


def _minmax_source(name: str, compare_name: str, mux_name: str,
                   width: int) -> str:
    lines = [f"circuit {name}:",
             f"  inputs {_pins('A', width)}, {_pins('B', width)}",
             f"  outputs {_pins('MIN', width)}, {_pins('MAX', width)}"]
    compare_inputs = ", ".join(
        [*(f"A{i}=A{i}" for i in range(width)),
         *(f"B{i}=B{i}" for i in range(width))])
    lines.append(
        f"  use {compare_name} compare({compare_inputs}) "
        "-> (LT=_a_lt_b, EQ=_equal, GT=_a_gt_b)")

    def mux_args(d0: str, d1: str) -> str:
        return ", ".join(
            [*(f"D0{i}={d0}{i}" for i in range(width)),
             *(f"D1{i}={d1}{i}" for i in range(width)), "S=_a_lt_b"])

    min_outputs = ", ".join(f"Y{i}=MIN{i}" for i in range(width))
    max_outputs = ", ".join(f"Y{i}=MAX{i}" for i in range(width))
    lines.append(f"  use {mux_name} minimum({mux_args('B', 'A')}) -> ({min_outputs})")
    lines.append(f"  use {mux_name} maximum({mux_args('A', 'B')}) -> ({max_outputs})")
    return "\n".join(lines) + "\n"


def build_comparator(name: str, width: int) -> ET.Element:
    """MSB-first priority chain with three straight state rails."""
    s = Schematic(name)
    s.text(f"{width}-bit unsigned magnitude comparator", (700, 60))
    center = 80 + 30 * width
    s.pin("A", (60, center), width=width)
    s.pin("B", (60, center + 100), width=width)
    amap = reverse_bits(width)
    a = s.splitter((140, center), width, width, "east", spacing=6,
                   bit_map=amap)
    b = s.splitter((220, center + 20), width, width, "east", spacing=6,
                   bit_map=amap)
    s.wire((60, center), a["combined"])
    s.wire((60, center + 100), (200, center + 100),
           (200, center + 20), b["combined"])
    for bit in range(width):
        short_tunnel(s, f"A{bit}", a[f"end{width - 1 - bit}"],
                     (220, a[f"end{width - 1 - bit}"][1]))
        short_tunnel(s, f"B{bit}", b[f"end{width - 1 - bit}"],
                     (280, b[f"end{width - 1 - bit}"][1]))

    stage_y = 320
    anchors = [(650 + 300 * index, stage_y) for index in range(width)]
    for index, bit in enumerate(range(width - 1, -1, -1)):
        x, y = anchors[index]
        s.instance("dp_compare_stage", f"bit{bit}", (x, y))
        input_x = x - circuitc.INST_W
        short_tunnel(s, f"A{bit}", (input_x, y + 60),
                     (input_x - 100, y + 60))
        s.tunnel(f"B{bit}", (input_x - 60, y + 120), facing="east")
        s.wire((input_x - 60, y + 120), (input_x - 20, y + 120),
               (input_x - 20, y + 80), (input_x, y + 80))
        if index:
            previous_x, _ = anchors[index - 1]
            for lane in range(3):
                s.wire((previous_x, y + 20 * lane),
                       (input_x, y + 20 * lane))

    first_input_x = anchors[0][0] - circuitc.INST_W
    for value, y in ((0, stage_y), (1, stage_y + 20), (0, stage_y + 40)):
        s.comp("0", "Constant", (first_input_x - 60, y), value=f"0x{value}")
        s.wire((first_input_x - 60, y), (first_input_x, y))

    last_x, _ = anchors[-1]
    output_x = last_x + 180
    for lane, label in enumerate(("LT", "EQ", "GT")):
        y = stage_y + 20 * lane
        s.pin(label, (output_x, y), output=True)
        s.wire((last_x, y), (output_x, y))
    return s.circuit


def build_mux_bank(name: str, width: int) -> ET.Element:
    """Regular vertical bank of scalar mux cells with real bus splitters."""
    s = Schematic(name)
    s.text(f"{width}-bit 2:1 selector", (300, 60))
    first_y = 180
    pitch = 80
    center = first_y + pitch * (width // 2)
    s.pin("D0", (60, center), width=width)
    s.pin("D1", (60, center + 100), width=width)
    s.pin("S", (60, first_y + pitch * width + 80))
    mapping = reverse_bits(width)
    d0 = s.splitter((140, center), width, width, "east",
                    spacing=8, bit_map=mapping)
    d1 = s.splitter((220, center + 20), width, width, "east",
                    spacing=8, bit_map=mapping)
    out = s.splitter((700, center), width, width, "west",
                     spacing=8, bit_map=mapping)
    s.wire((60, center), d0["combined"])
    s.wire((60, center + 100), (200, center + 100),
           (200, center + 20), d1["combined"])
    s.wire(out["combined"], (820, center))
    s.pin("Y", (820, center), width=width, output=True)

    select_y = first_y + pitch * width + 80
    select_x = 330
    s.wire((60, select_y), (select_x, select_y),
           (select_x, first_y + 40))
    for row, bit in enumerate(range(width - 1, -1, -1)):
        y = first_y + pitch * row
        s.instance("dp_mux2", f"bit{bit}", (600, y))
        port_x = 600 - circuitc.INST_W
        s.wire(d0[f"end{width - 1 - bit}"], (port_x, y))
        s.wire(d1[f"end{width - 1 - bit}"], (port_x, y + 20))
        s.wire((select_x, y + 40), (port_x, y + 40))
        s.wire((600, y), out[f"end{width - 1 - bit}"])
    return s.circuit


def build_minmax(name: str, compare_name: str, mux_name: str,
                 width: int) -> ET.Element:
    """Block-level compare-and-select datapath."""
    s = Schematic(name)
    s.text(f"minimum / maximum of two {width}-bit unsigned values", (430, 70))
    s.text("compare", (560, 180))
    s.text("select minimum", (1100, 340))
    s.text("select maximum", (1100, 560))
    s.pin("A", (60, 260), width=width)
    s.pin("B", (60, 380), width=width)
    s.pin("MIN", (1500, 420), width=width, output=True)
    s.pin("MAX", (1500, 640), width=width, output=True)
    short_tunnel(s, "A_BUS", (60, 260), (150, 260), width=width)
    short_tunnel(s, "B_BUS", (60, 380), (150, 380), width=width)

    s.instance(compare_name, "compare", (700, 260))
    s.tunnel("A_BUS", (400, 240), width=width, facing="east")
    s.wire((400, 240), (450, 240), (450, 260), (480, 260))
    s.tunnel("B_BUS", (400, 300), width=width, facing="east")
    s.wire((400, 300), (460, 300), (460, 280), (480, 280))
    short_tunnel(s, "A_LT_B", (700, 260), (770, 260))
    for y in (280, 300):
        s.wire((700, y), (760, y))
        s.comp("0", "Probe", (760, y), facing="west")

    for label, y, d0, d1 in (("minimum", 420, "B_BUS", "A_BUS"),
                              ("maximum", 640, "A_BUS", "B_BUS")):
        s.instance(mux_name, label, (1250, y))
        s.tunnel(d0, (900, y - 40), width=width, facing="east")
        s.wire((900, y - 40), (950, y - 40), (950, y), (1030, y))
        short_tunnel(s, d1, (1030, y + 20), (900, y + 20), width=width)
        s.tunnel("A_LT_B", (900, y + 80), facing="east")
        s.wire((900, y + 80), (970, y + 80),
               (970, y + 40), (1030, y + 40))
    s.wire((1250, 420), (1500, 420))
    s.wire((1250, 640), (1500, 640))
    return s.circuit


def expand(requests: list[Request], main: str) -> Expansion:
    needs_compare = any(
        r.template in ("unsigned_comparator", "unsigned_minmax")
        for r in requests)
    needs_mux = any(
        r.template in ("mux2", "unsigned_minmax") for r in requests)
    blocks = []
    if needs_compare:
        blocks.append(_compare_stage_source())
    if needs_mux:
        blocks.append(_mux2_source())
    layouts = {}
    internal_names = set()
    public_names = {request.name for request in requests}
    reserved = set()
    if needs_compare:
        reserved.add("dp_compare_stage")
    if needs_mux:
        reserved.add("dp_mux2")
    collision = sorted(public_names & reserved)
    if collision:
        raise ValueError(f"public names collide with template leaves: {collision}")
    for request in requests:
        if request.template == "mux2":
            blocks.append(_mux_bank_source(request.name, request.width))
            layouts[request.name] = build_mux_bank(
                request.name, request.width)
        elif request.template == "unsigned_comparator":
            blocks.append(_comparator_source(request.name, request.width))
            layouts[request.name] = build_comparator(request.name, request.width)
        else:
            compare_name = f"{request.name}_compare"
            mux_name = f"{request.name}_mux"
            internal_names.update((compare_name, mux_name))
            blocks.extend((_comparator_source(compare_name, request.width),
                           _mux_bank_source(mux_name, request.width),
                           _minmax_source(request.name, compare_name,
                                          mux_name, request.width)))
            layouts[compare_name] = build_comparator(compare_name, request.width)
            layouts[mux_name] = build_mux_bank(mux_name, request.width)
            layouts[request.name] = build_minmax(
                request.name, compare_name, mux_name, request.width)
    collision = sorted(public_names & internal_names)
    if collision:
        raise ValueError(f"public names collide with generated helpers: {collision}")
    return Expansion(blocks, layouts, requests, main)


def _verification_pairs(width: int) -> list[tuple[int, int]]:
    if width <= 4:
        return [(a, b) for a in range(1 << width)
                for b in range(1 << width)]
    mask = (1 << width) - 1
    values = {0, 1, 2, mask, max(0, mask - 1)}
    for bit in range(width):
        values.update((1 << bit, max(0, (1 << bit) - 1)))
    pairs = [(a, b) for a in sorted(values) for b in sorted(values)]
    for i in range(128):
        pairs.append(((73 * i + 19) & mask, (151 * i + 41) & mask))
    return list(dict.fromkeys(pairs))


def verify(root, expansion: Expansion) -> dict:
    rows = 0
    by_circuit = {}
    for request in expansion.requests:
        count = 0
        for a, b in _verification_pairs(request.width):
            if request.template == "mux2":
                for select in (0, 1):
                    out = evaluate_circuit(
                        root, request.name, {"D0": a, "D1": b, "S": select})
                    expected = {"Y": b if select else a}
                    if out != expected:
                        raise ValueError(
                            f"{request.name} mismatch D0={a} D1={b} "
                            f"S={select}: {out} != {expected}")
                    count += 1
                continue
            out = evaluate_circuit(root, request.name, {"A": a, "B": b})
            if request.template == "unsigned_comparator":
                expected = {"LT": int(a < b), "EQ": int(a == b),
                            "GT": int(a > b)}
            else:
                expected = {"MIN": min(a, b), "MAX": max(a, b)}
            if out != expected:
                raise ValueError(
                    f"{request.name} mismatch A={a} B={b}: {out} != {expected}")
            count += 1
        rows += count
        by_circuit[request.name] = count
    return {"ok": True, "vectors": rows, "circuits": by_circuit}


def build(spec: dict, circ_path: str | Path,
          logic_path: str | Path | None = None) -> dict:
    """Generate, structurally check, and physically evaluate a datapath spec."""
    requests, main = parse_spec(spec)
    expansion = expand(requests, main)
    source = "\n".join(expansion.source_blocks)
    definitions = circuitc.parse_logic(source)
    nets = [circuitc.compile_netlist(definition) for definition in definitions]
    circ_path = Path(circ_path)
    if logic_path is None:
        logic_path = circ_path.with_suffix(".logic")
    logic_path = Path(logic_path)
    logic_path.write_text(source)
    circ_path.write_text(circuitc.emit_project(nets))

    tree, root = circuitc._load(circ_path)
    for name, replacement in expansion.layouts.items():
        old = circuitc._circ(root, name)
        if old is None:
            raise ValueError(f"generated scalar target {name!r} is missing")
        index = list(root).index(old)
        root.remove(old)
        root.insert(index, replacement)
    root.find("main").set("name", main)
    circuitc._rewrite(tree, str(circ_path))
    checks = circuitc.check_all(str(circ_path))
    if not checks["ok"]:
        raise ValueError(f"generated datapath failed structural checks: {checks}")
    behavior = verify(ET.parse(circ_path).getroot(), expansion)
    return {
        "ok": checks["ok"] and behavior["ok"],
        "circ": str(circ_path.resolve()),
        "logic": str(logic_path.resolve()),
        "main": main,
        "templates": [request.template for request in requests],
        "checks": circuitc._check_summary(checks)["checks"],
        "physical_behavior": behavior,
    }
